### ISSUE TITLE
Pull request club 

### ISSUE THREAD

**Issue by yewtc** [neilb/WebService-HackerNews#8]
I got assigned this module for my December pull request club task. I had intended to work on on post Christmas - which  I agree was cutting it fine, but have been struck down by a lurgy since then and taken away all my time.

 Anyway, you have two open issues:
1.  Adding travis tests and 
2.  Adding support for the updated API.

But an   open pull request  for each  of them so I 'm not quite sure what to do. Maybe tests using git hubs actions?

**Comment by neilb** [comment]
How about:

* improving test coverage?
* seeing if there's anything useful that could be added to SEE ALSO?
*
